# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:current-alpine3.21 AS builder

# Must be entire project because `prepare` script is run during `npm install` and requires all files.
COPY . /app
COPY tsconfig.json /tsconfig.json

WORKDIR /app

RUN --mount=type=cache,target=/root/.npm npm install

FROM node:current-alpine3.21 AS release

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

ENV NODE_ENV=production

WORKDIR /app

RUN npm ci --ignore-scripts --omit-dev

# Expose port for SSE transport mode
EXPOSE 8080

ENTRYPOINT ["node", "dist/index.js"]
